flags: {}
packages:
- '.'
extra-deps:
- GLURaw-1.5.0.2
- GLUT-2.7.0.3
- ObjectName-1.1.0.0
- OpenGL-2.12.0.1
- OpenGLRaw-2.5.5.0
- bmp-1.2.5.2
- bytes-0.15.0.1
- frpnow-0.18
- frpnow-gloss-0.12
- gloss-1.9.4.1
- gloss-rendering-1.9.3.1
- lens-4.13
- linear-1.20.2
- parallel-3.2.0.6
- reflection-2.1
- vector-0.11.0.0
resolver: ghc-7.10
